---
openapi: 3.0.1
info:
  title: Swaggerize API
  version: v1
paths:
  "/users":
    get:
      summary: list users
      tags:
      - User
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                profession:
                  type: string
                avatar:
                  type: string
                bio:
                  type: string
              required:
              - name
              - email
              - password
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - User
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                profession:
                  type: string
                avatar:
                  type: string
                bio:
                  type: string
    delete:
      summary: delete user
      tags:
      - User
      responses:
        '200':
          description: successful
servers:
- url: "{local}"
  variables:
    local:
      default: http://localhost:3000
